apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-curso-docker-config
  namespace: profesor
data:
  JAVA_OPTS: "-Xmx256m"
  MESSAGE: "hola container1 para la prueba del ingress"
  DB: "190.0.44.5"
  TZ: "America/Lima"
