apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-curso-docker-hpa
  namespace: profesor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-curso-docker-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50