apiVersion: v1
kind: Service
metadata:
  name: ms-curso-docker2-service
  namespace: profesor
spec:
  selector:
    app: ms-curso-docker2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
